debug: true

web:
  host: 127.0.0.1
  port: 8085

bot:
  token: ${BOT_TOKEN}

database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5433}
  database: ${DB_NAME:svoya_igra}
  user: ${DB_USER:postgres}
  password: ${DB_PASSWORD}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

session:
  key: ${SESSION_KEY:super-secret-session-key-change-me}

store: {}